logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/HemodialDB?serverTimezone=Europe/Paris&createDatabaseIfNotExist=true
    password: ''
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp-mail.outlook.com
    password: 'Azerty123456'
    username: prodialyse@outlook.com
    properties:
      mail:
        store:
          protocol: pop3
        smtp:
          connecttimeout: 5000
          timeout: 30000
          writetimeout: 5000
          auth: true
          port: 587
          starttls:
            enable: true


  variables:
    secretKey: "3F4528472B4B6250655368566D597133743677397A24432646294A404D635166"
    expiredTime: 86400000
